#
# Makefile for the Linux dazukofs-filesystem routines.
#

obj-$(CONFIG_DAZUKOFS_FS) += dazukofs.o

dazukofs-objs := super.o inode.o file.o dentry.o mmap.o event.o \
		 dev.o group_dev.o ctrl_dev.o ign_dev.o
